// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VocabApp.API.Data;

#nullable disable

namespace VocabApp.API.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260522152516_FixStageOffsetAfterDay4Interval")]
    partial class FixStageOffsetAfterDay4Interval
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VocabApp.API.Models.DailyProgress", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("WordCount")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "Date");

                    b.ToTable("DailyProgress");
                });

            modelBuilder.Entity("VocabApp.API.Models.SetProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("FirstStudiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("KnownCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastStudiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("NextReviewAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ReviewStage")
                        .HasColumnType("integer");

                    b.Property<Guid>("SetId")
                        .HasColumnType("uuid");

                    b.Property<int>("TotalWords")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SetId");

                    b.HasIndex("UserId", "NextReviewAt");

                    b.HasIndex("UserId", "SetId")
                        .IsUnique();

                    b.ToTable("SetProgress");
                });

            modelBuilder.Entity("VocabApp.API.Models.SetStudyLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("KnownCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("NextReviewAtAfter")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SetId")
                        .HasColumnType("uuid");

                    b.Property<int>("StageAfter")
                        .HasColumnType("integer");

                    b.Property<int>("StageBefore")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StudiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TotalWords")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SetId");

                    b.HasIndex("UserId", "SetId");

                    b.HasIndex("UserId", "SetId", "StudiedAt");

                    b.ToTable("SetStudyLogs");
                });

            modelBuilder.Entity("VocabApp.API.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GoogleId")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("GoogleId")
                        .IsUnique()
                        .HasFilter("\"GoogleId\" IS NOT NULL");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("VocabApp.API.Models.UserSet", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SetId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AddedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("UserId", "SetId");

                    b.HasIndex("SetId");

                    b.ToTable("UserSets");
                });

            modelBuilder.Entity("VocabApp.API.Models.Word", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Definition")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Example")
                        .HasColumnType("text");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<Guid>("SetId")
                        .HasColumnType("uuid");

                    b.Property<string>("Term")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SetId");

                    b.ToTable("Words");
                });

            modelBuilder.Entity("VocabApp.API.Models.WordProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("KnownCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastSeenAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("UnknownCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WordId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WordId");

                    b.HasIndex("UserId", "WordId")
                        .IsUnique();

                    b.ToTable("WordProgress");
                });

            modelBuilder.Entity("VocabApp.API.Models.WordSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("IsPublic");

                    b.HasIndex("OwnerId");

                    b.ToTable("WordSets");
                });

            modelBuilder.Entity("VocabApp.API.Models.DailyProgress", b =>
                {
                    b.HasOne("VocabApp.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("VocabApp.API.Models.SetProgress", b =>
                {
                    b.HasOne("VocabApp.API.Models.WordSet", "Set")
                        .WithMany("Progress")
                        .HasForeignKey("SetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VocabApp.API.Models.User", "User")
                        .WithMany("Progress")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Set");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VocabApp.API.Models.SetStudyLog", b =>
                {
                    b.HasOne("VocabApp.API.Models.WordSet", "Set")
                        .WithMany()
                        .HasForeignKey("SetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VocabApp.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Set");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VocabApp.API.Models.UserSet", b =>
                {
                    b.HasOne("VocabApp.API.Models.WordSet", "Set")
                        .WithMany("SavedBy")
                        .HasForeignKey("SetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VocabApp.API.Models.User", "User")
                        .WithMany("SavedSets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Set");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VocabApp.API.Models.Word", b =>
                {
                    b.HasOne("VocabApp.API.Models.WordSet", "Set")
                        .WithMany("Words")
                        .HasForeignKey("SetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Set");
                });

            modelBuilder.Entity("VocabApp.API.Models.WordProgress", b =>
                {
                    b.HasOne("VocabApp.API.Models.User", "User")
                        .WithMany("WordProgress")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VocabApp.API.Models.Word", "Word")
                        .WithMany("Progress")
                        .HasForeignKey("WordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Word");
                });

            modelBuilder.Entity("VocabApp.API.Models.WordSet", b =>
                {
                    b.HasOne("VocabApp.API.Models.User", "Owner")
                        .WithMany("OwnedSets")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("VocabApp.API.Models.User", b =>
                {
                    b.Navigation("OwnedSets");

                    b.Navigation("Progress");

                    b.Navigation("SavedSets");

                    b.Navigation("WordProgress");
                });

            modelBuilder.Entity("VocabApp.API.Models.Word", b =>
                {
                    b.Navigation("Progress");
                });

            modelBuilder.Entity("VocabApp.API.Models.WordSet", b =>
                {
                    b.Navigation("Progress");

                    b.Navigation("SavedBy");

                    b.Navigation("Words");
                });
#pragma warning restore 612, 618
        }
    }
}
